// Code generated by hertz generator.

package main

import (
	"context"

	handler "github.com/0623-github/dk_ai/biz/handler"
	"github.com/0623-github/dk_ai/biz/wrapper"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	h := server.Default()
	wrapper := wrapper.NewImpl(context.Background())
	handler := &handler.Handler{Wrapper: wrapper}
	register(h, handler)
	h.Spin()
}
