// Code generated by hertz generator. DO NOT EDIT.

package main

import (
	handler "github.com/0623-github/dk_ai/biz/handler"
	router "github.com/0623-github/dk_ai/biz/router"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// register registers all routers.
func register(r *server.Hertz, h *handler.Handler) {

	router.GeneratedRegister(r)

	customizedRegister(r, h)
}
