// Code generated by hertz generator.

package main

import (
	handler "github.com/0623-github/dk_ai/biz/handler"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz, wrapper *handler.Handler) {
	// 健康检查
	r.GET("/ping", handler.Ping)

	// 聊天接口
	r.POST("/chat", wrapper.Chat)
	r.POST("/chat/stream", wrapper.ChatStream)

	// 会话管理
	r.POST("/api/sessions", wrapper.CreateSession)
	r.GET("/api/sessions", wrapper.ListSessions)
	r.GET("/api/session", wrapper.GetSession)
	r.PUT("/api/sessions/:id", wrapper.UpdateSession)
	r.DELETE("/api/sessions/:id", wrapper.DeleteSession)

	// 消息管理
	r.GET("/api/messages", wrapper.GetMessages)
}
