// Code generated by hertz generator.

package main

import (
	handler "github.com/0623-github/dk_ai/biz/handler"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz, wrapper *handler.Handler) {
	r.GET("/ping", handler.Ping)
	r.POST("/chat", wrapper.Chat)

}
